service:
  name: eksservice
  identifier: hello_python
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          type: Ecr
          spec:
            connectorRef: aws_ecr
            region: us-east-1
            imagePath: 186463824337.dkr.ecr.us-east-1.amazonaws.com/ecr_kareem_repo
            tag: <+pipeline.variables.IMAGE_TAG>
      manifests:
        - manifest:
            identifier: k8s
            type: K8sManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: repo_git
                  gitFetchType: Branch
                  branch: main
                  paths:
                    - k8s
              skipResourceVersioning: false
